// db/tom.js — Theory of Machines (2 concepts)

MECHVIZ_DB.concepts.push(

  {
    id: "gear-trains", title: "Gear Trains",
    category: "tom", icon: "⚙️",
    tags: ["TOM", "gears", "gear ratio", "torque", "speed", "transmission"],
    shortDesc: "Transmitting torque and changing speed between shafts — the fundamental mechanical power transmission element.",
    theory: {
      definition: "A gear train is a set of two or more gears meshing together to transmit rotational motion and torque between shafts. By choosing the number of teeth on each gear, both speed (angular velocity) and torque can be transformed — at the cost of mechanical losses. Gear trains are found in virtually every machine: from wristwatches to wind turbines, from car gearboxes to industrial robots.",
      keyConcepts: [
        { term: "Gear Ratio (G.R.)", desc: "G.R. = N_driver/N_driven = T_driven/T_driver = ω_driver/ω_driven. If G.R. > 1: speed reduction, torque multiplication. If G.R. < 1: speed increase, torque reduction. Power is conserved (P = T×ω): what you gain in torque you lose in speed, and vice versa." },
        { term: "Module (m)", desc: "m = d_pitch / T (pitch diameter / number of teeth). The standardised tooth size parameter. Two gears can only mesh if they have the same module. Standard module values (in mm): 1, 1.25, 1.5, 2, 2.5, 3, 4, 5, 6, 8, 10, 12, 16, 20." },
        { term: "Involute Tooth Profile", desc: "All standard gears use involute tooth flanks — generated by unwinding a taut string from the base circle. Key property: the contact normal always passes through the pitch point, giving a constant velocity ratio regardless of centre distance variation (manufacturing tolerance compensation)." },
        { term: "Planetary (Epicyclic) Gear Train", desc: "Consists of sun gear, planet gears, ring gear, and carrier. Multiple components can be input/output/fixed, giving many configurations. Very high gear ratios in compact packages. Used in automatic transmissions, wind turbines, and robot joints." }
      ],
      formulas: [
        { name: "Gear Ratio (Simple)", eq: "G.R. = T₂/T₁ = N₁/N₂ = ω₁/ω₂", variables: { "T": "Number of teeth", "N": "Speed (RPM)", "ω": "Angular velocity (rad/s)" } },
        { name: "Output Torque", eq: "τ_out = τ_in × G.R. × η", variables: { "η": "Mechanical efficiency (0.95–0.99 per stage for spur gears)" } },
        { name: "Compound Train Velocity Ratio", eq: "VR = (T₂ × T₄ × T₆...) / (T₁ × T₃ × T₅...)", variables: { "T_odd": "Driver gear teeth", "T_even": "Driven gear teeth per stage" } },
        { name: "Pitch Circle Diameter", eq: "d = m × T", variables: { "m": "Module (mm)", "T": "Number of teeth", "d": "Pitch diameter (mm)" } },
        { name: "Centre Distance", eq: "C = (d₁ + d₂)/2 = m(T₁ + T₂)/2", variables: { "C": "Centre distance between gear shafts (mm)" } }
      ],
      explanation: "Two meshing gears have their pitch circles rolling on each other without slipping. This kinematic constraint means ω₁×r₁ = ω₂×r₂ (pitch line velocities equal) → G.R. = r₂/r₁ = T₂/T₁. For compound gear trains, the ratio of each stage multiplies: a two-stage train with 4:1 and 5:1 ratios gives 20:1 overall. Epicyclic trains are more complex: using the Tabular Method (fixing/releasing different members) gives the gear ratio for each configuration. A simple 3-shaft epicyclic can give ratios from 1:1 to 1:10+ depending on which shaft is input, output, and fixed."
    },
    practicalRules: [
      "Efficiency per gear stage (spur/helical gears): <strong>97–99%</strong>. Worm gears: <strong>50–90%</strong> depending on helix angle.",
      "Minimum number of teeth to avoid undercutting (20° pressure angle): <strong>T_min = 17</strong> for full-depth involute teeth.",
      "For smooth operation: gear ratio per stage should not exceed <strong>6:1 for spur, 8:1 for helical</strong>. Higher ratios use compound trains.",
      "Module selection rule: m ≥ <strong>√(T/σ_b) × constant</strong> — larger module for higher torque and bending loads.",
      "Gear noise: spur gears are louder than helical (parallel vs gradual tooth engagement). Double-helical (herringbone) gears are quietest and eliminate axial thrust.",
      "Backlash: standard gears have 0.1–0.3 mm backlash. Anti-backlash gears (spring-loaded split gears) are used in CNC and robotics for positioning accuracy."
    ],
    workedExample: {
      problem: "A 3-stage compound gear train drives a load at 50 RPM from a motor running at 1440 RPM. Stage 1 driver has T₁=20 teeth. The overall gear ratio must be achieved with equal ratios per stage. Find the number of teeth on each driven gear (assuming driver gears each have 20 teeth) and the output torque if motor torque = 8 N·m, overall efficiency = 0.96.",
      given: ["N_input = 1440 RPM, N_output = 50 RPM", "3 stages, each driver gear T = 20 teeth", "Motor torque τ_in = 8 N·m", "Overall efficiency η = 0.96"],
      steps: [
        { text: "Find overall gear ratio:", calc: "G.R._total = N_input / N_output = 1440 / 50 = 28.8" },
        { text: "Equal ratio per stage (ratio = (G.R.)^(1/3)):", calc: "G.R._per_stage = 28.8^(1/3) = 3.065 ≈ 3.065:1 per stage" },
        { text: "Find number of teeth on each driven gear (T_driver = 20 each):", calc: "T_driven = T_driver × G.R._per_stage = 20 × 3.065 = 61.3 → round to 61 teeth\nActual ratio per stage = 61/20 = 3.05\nActual overall ratio = 3.05³ = 28.37 ≈ 28.37:1" },
        { text: "Calculate actual output speed:", calc: "N_output = 1440 / 28.37 = 50.75 RPM (close to target of 50 RPM)" },
        { text: "Calculate output torque:", calc: "τ_out = τ_in × G.R. × η = 8 × 28.37 × 0.96 = 218.0 N·m" }
      ],
      answer: "Each driven gear needs 61 teeth. Actual overall ratio ≈ 28.4:1, output speed ≈ 50.7 RPM, output torque ≈ 218 N·m. The gear train amplifies torque by 28.4× while reducing speed by the same factor."
    },
    commonMistakes: [
      { title: "Confusing gear ratio with velocity ratio in compound trains", desc: "In a compound train, idle gears (on the same shaft as the next driver) do NOT affect the velocity ratio. Only the first driver and last driven gear define the overall ratio. Students often multiply all tooth counts together including idle gears, getting wrong answers." },
      { title: "Forgetting efficiency losses stack multiplicatively", desc: "If each stage has 98% efficiency, a 3-stage train has η_total = 0.98³ = 0.941 — NOT 3×0.98. Efficiency losses compound. A 5-stage worm drive at 80% per stage gives η_total = 0.8⁵ = 0.33 — only 33% overall efficiency." },
      { title: "Mixing up module and diametral pitch", desc: "Module (metric) = pitch diameter / tooth count. Diametral pitch (imperial) = tooth count / pitch diameter (inches) — the inverse relationship! Module = 25.4 / Diametral pitch. Using one when the other is required gives gears that physically cannot mesh." }
    ],
    simulation: "gears",
    realWorldUses: [
      { title: "Automotive Manual Gearbox", icon: "🚗", description: "A 5-speed gearbox uses a layshaft compound gear train. 1st gear ≈ 3.5:1 (high torque for starting). 5th gear ≈ 0.7:1 (overdrive for cruising). The driver selects which gear pair is engaged via synchroniser rings, changing the effective gear ratio and thus the torque-speed balance." },
      { title: "Wind Turbine Gearbox", icon: "🌀", description: "A 3 MW wind turbine rotor spins at 12–15 RPM. The generator needs 1500 RPM. The gearbox (typically 3-stage planetary + 2 helical stages) provides ~100:1 ratio in a compact unit weighing ~70 tonnes mounted 80 m above ground." },
      { title: "Industrial Robot Wrist", icon: "🤖", description: "Each of the 6 axes of an industrial robot uses a harmonic drive gear (a special strain-wave gear providing 100:1 to 320:1 ratio in a thin, lightweight package with zero backlash — essential for ±0.05 mm repeatability)." },
      { title: "Mechanical Watch Gear Train", icon: "⌚", description: "A Swiss lever escapement watch has a gear train with ~7 stages, with the seconds wheel turning at 1 RPM, the minute wheel at 1/60 RPM, and the hour wheel at 1/720 RPM — all derived from the mainspring through precisely calculated tooth counts, accurate to seconds per day." }
    ],
    resources: [
      { label: "Gear Trains — The Efficient Engineer", url: "https://www.youtube.com/watch?v=odpsm3ybPsA", type: "video" },
      { label: "NPTEL — Theory of Machines (IIT Delhi)", url: "https://nptel.ac.in/courses/112105127", type: "course" },
      { label: "MIT OCW — Machine Elements", url: "https://ocw.mit.edu/courses/2-72-elements-of-mechanical-design-spring-2009/", type: "course" },
      { label: "Engineering Toolbox — Gear Design", url: "https://www.engineeringtoolbox.com/gear-ratio-efficiency-d_1406.html", type: "article" }
    ]
  },

  {
    id: "cam-follower", title: "Cam & Follower Mechanism",
    category: "tom", icon: "🎡",
    tags: ["TOM", "cam", "follower", "motion", "displacement diagram", "mechanism"],
    shortDesc: "Converting uniform rotation into precise, programmed reciprocating motion — the heart of every engine valve train.",
    theory: {
      definition: "A cam is a rotating or sliding machine element that imparts a desired motion to another element called the follower. By shaping the cam profile precisely, any desired follower displacement, velocity, and acceleration can be achieved for any portion of the cam rotation cycle. Cams are the most versatile motion generation devices — they can produce constant velocity, simple harmonic motion, cycloidal, or any user-defined motion law.",
      keyConcepts: [
        { term: "Displacement Diagram", desc: "The fundamental design tool: a plot of follower displacement (y-axis) vs. cam angle (x-axis) for one complete revolution. It shows rise, dwell, and return phases. The cam profile is generated by geometrically inverting this diagram." },
        { term: "Pressure Angle (α)", desc: "The angle between the follower axis and the normal to the cam profile at the point of contact. Higher pressure angle → higher side thrust on follower → jamming risk. Design limit: α ≤ 30° for translating followers, ≤ 45° for oscillating followers." },
        { term: "Jerk (da/dt)", desc: "Rate of change of acceleration. Determines inertia forces that arise from acceleration changes — these excite vibration. Cycloidal and modified trapezoidal profiles have finite jerk (smooth). SHM and parabolic profiles have infinite jerk at endpoints (discontinuous acceleration). Low jerk is critical at high cam speeds." },
        { term: "Base Circle & Pitch Curve", desc: "Base circle: smallest circle centred on cam axis, tangent to cam profile. Pitch curve: path traced by roller centre (for roller follower). Cam profile = offset of pitch curve by roller radius. Larger base circle → lower pressure angle (better) but larger, heavier cam." }
      ],
      formulas: [
        { name: "SHM Rise Displacement", eq: "y = (h/2)[1 − cos(πθ/β)]", variables: { "h": "Total rise (mm)", "θ": "Current cam angle (°)", "β": "Angle for full rise (°)" } },
        { name: "SHM Velocity", eq: "v = (πhω/2β) · sin(πθ/β)", variables: { "ω": "Cam angular velocity (rad/s)" } },
        { name: "SHM Acceleration", eq: "a = (π²hω²/2β²) · cos(πθ/β)", variables: { "a": "Follower acceleration (m/s²)" } },
        { name: "Cycloidal Rise Displacement", eq: "y = h[θ/β − (1/2π)·sin(2πθ/β)]", variables: { "Advantage": "Finite acceleration, zero jerk at endpoints" } },
        { name: "Pressure Angle (Translating Follower)", eq: "tan α = (dy/dθ − e) / (r_b + y)", variables: { "e": "Follower offset from cam axis (mm)", "r_b": "Base circle radius (mm)" } }
      ],
      explanation: "The design process starts with the motion requirement: how much rise, how fast, with what velocity and acceleration characteristics, and what dwell periods are needed. The displacement diagram is drawn, then mathematically expressed using a chosen motion law (SHM, cycloidal, polynomial). Differentiating gives velocity and acceleration curves. The acceleration curve is critical — it determines the contact force between cam and follower via F = m×a. For the follower to remain in contact (no 'jump'), the spring force must exceed the inertia force at all points where the cam pushes the follower back: k > m×a_max / (x_min spring compression). The cam profile is then generated by geometrically inverting the displacement diagram — rotating the follower around the fixed cam and plotting the cam boundary."
    },
    practicalRules: [
      "Choose <strong>cycloidal</strong> motion law for high-speed cams (smooth acceleration, finite jerk).",
      "Choose <strong>SHM</strong> for low-speed applications where jerk is tolerable and profile is simpler.",
      "Pressure angle limit: <strong>≤ 30°</strong> for translating followers. Increase base circle radius to reduce pressure angle.",
      "Spring must satisfy: <strong>k·x_min > m·a_max</strong> (follower must stay in contact at all points).",
      "Critical speed: follower will jump off cam if cam speed exceeds <strong>ω_crit = √(k/m)</strong> × (correction factor) — always check.",
      "Minimum base circle radius to avoid undercutting: for roller follower, pitch curve radius of curvature must everywhere exceed roller radius."
    ],
    workedExample: {
      problem: "A cam with SHM follower motion must rise 30 mm in 120° of cam rotation, dwell for 60°, and return in 120° (remaining 60° is bottom dwell). Cam speed = 200 RPM. Find maximum velocity and maximum acceleration during the rise.",
      given: ["h = 30 mm = 0.03 m", "β (rise) = 120° = 2π/3 rad", "N = 200 RPM → ω = 2π×200/60 = 20.94 rad/s"],
      steps: [
        { text: "SHM rise velocity: v = (πhω)/(2β) × sin(πθ/β). Maximum occurs at θ = β/2 (mid-rise), where sin = 1:", calc: "v_max = π × 0.03 × 20.94 / (2 × 2π/3)\nv_max = π × 0.03 × 20.94 / (4π/3)\nv_max = 0.03 × 20.94 × 3/4 = 0.471 m/s" },
        { text: "SHM rise acceleration: a = (π²hω²)/(2β²) × cos(πθ/β). Maximum at θ = 0 (start of rise), where cos = 1:", calc: "a_max = π² × 0.03 × (20.94)² / (2 × (2π/3)²)\na_max = 9.87 × 0.03 × 438.5 / (2 × 4.386)\na_max = 129.9 / 8.77 = 14.81 m/s²" },
        { text: "Compare with gravity (9.81 m/s²):", calc: "a_max = 14.81 m/s² = 1.51 g\nThis means inertia force on follower = 1.51 times its weight at start of rise. Spring must overcome this." }
      ],
      answer: "v_max = 0.471 m/s (at θ = 60°, mid-rise). a_max = 14.81 m/s² = 1.51g (at θ = 0°, start of rise). The spring must exert a force > 1.51 × m_follower × 9.81 N to prevent follower jump at this speed."
    },
    commonMistakes: [
      { title: "Using degrees instead of radians in angular velocity calculations", desc: "ω in all follower velocity and acceleration formulas must be in rad/s. If N = 300 RPM, then ω = 2π×300/60 = 31.4 rad/s — NOT 300. Using RPM directly gives velocities 60/(2π) = 9.55 times too low." },
      { title: "Designing the cam profile without checking pressure angle", desc: "A theoretically correct displacement diagram can generate a cam that physically binds (pressure angle > 30°) or self-intersects (undercutting). Always plot the pressure angle variation and verify it stays below the design limit throughout the motion cycle." },
      { title: "Ignoring the return stroke when specifying follower spring", desc: "The spring must keep the follower on the cam during both rise and return. On the return stroke, the cam pushes the follower back — inertia tries to keep it elevated. The minimum spring preload must overcome this inertia force, or the follower 'floats' and impacts the cam when it drops." }
    ],
    simulation: "cam",
    realWorldUses: [
      { title: "IC Engine Valve Train", icon: "🔧", description: "Every petrol and diesel engine uses cams to open intake and exhaust valves. Variable Valve Timing (VTEC, VANOS) systems effectively change the cam profile electronically — using multiple cam lobes or phasing mechanisms to optimise valve lift and timing across the RPM range for power and efficiency." },
      { title: "Automatic Assembly Machines", icon: "🏭", description: "Cam-operated pick-and-place machines perform hundreds of cycles per minute. The cam profile controls the motion of grippers, feeders, and transfer arms — guaranteeing the same precise motion every cycle without sensors or electronics. A well-designed cam can last millions of cycles." },
      { title: "Textile Looms", icon: "🧵", description: "Dobby and jacquard loom mechanisms use arrays of cams to control individual warp-thread heddles in programmed sequences, creating complex fabric weave patterns at 500–1000 picks per minute. The entire woven pattern is 'encoded' in the cam profile shapes." },
      { title: "Shoe Manufacturing Machinery", icon: "👞", description: "Lasting machines that stretch the upper leather over the shoe last use cam-follower mechanisms to generate the complex 3D motion required to simultaneously tension, stretch, and cement the leather — a motion too complex for a simple crank mechanism." }
    ],
    resources: [
      { label: "Cams & Followers — NPTEL", url: "https://nptel.ac.in/courses/112105127", type: "course" },
      { label: "MIT OCW — Machine Design", url: "https://ocw.mit.edu/courses/2-72-elements-of-mechanical-design-spring-2009/", type: "course" },
      { label: "Cam Animation — 3D Visualisation (YouTube)", url: "https://www.youtube.com/watch?v=P1u-tLaILms", type: "video" },
      { label: "Engineering Toolbox — Cam Mechanisms", url: "https://www.engineeringtoolbox.com/cam-follower-d_1457.html", type: "article" }
    ]
  },

  {
    id: "four-bar-linkage", title: "Four-Bar Linkage Mechanism",
    category: "tom", icon: "🔗",
    tags: ["TOM", "mechanism", "four-bar", "Grashof", "linkage", "coupler"],
    shortDesc: "The simplest closed kinematic chain — the fundamental building block of almost every mechanism.",
    theory: {
      definition: "A four-bar linkage consists of four rigid links connected by four revolute (pin) joints forming a closed loop. One link is fixed (frame). The input link (crank or rocker) drives the coupler, which in turn drives the output link (follower). By choosing link lengths, virtually any desired output motion can be achieved. Four-bar linkages are the simplest and most common planar mechanisms — found in everything from windscreen wipers to steam engine valve gear.",
      keyConcepts: [
        { term: "Grashof's Condition", desc: "If s + l ≤ p + q (where s = shortest link, l = longest link, p, q = other two links), at least one link can make a full rotation. If s + l > p + q (non-Grashof), no link can make a full rotation — all links merely oscillate. Grashof's condition determines whether the mechanism is a crank-rocker, double-crank, double-rocker, or change-point mechanism." },
        { term: "Inversions", desc: "Fixing different links gives different mechanisms: (1) Fix link opposite shortest → crank-rocker (crank rotates fully, rocker oscillates). (2) Fix shortest link → double-crank (both adjacent links rotate). (3) Fix link adjacent to shortest → rocker-crank (or double-rocker). Each inversion has different output characteristics." },
        { term: "Transmission Angle (μ)", desc: "The angle between the coupler and the follower link. Optimal at μ = 90°. Poor transmission when μ < 40° or μ > 140° — mechanical advantage drops, force transmission becomes inefficient, and the mechanism may lock. Transmission angle is the key quality criterion in linkage design." },
        { term: "Coupler Curve", desc: "Any point on the coupler traces a closed curve called a coupler curve. By choosing the coupler point location, a vast variety of path shapes can be generated — including approximate straight lines (Watt's linkage), figure-8s, and cardioids. Coupler curves enable complex motion paths from simple pin joints." }
      ],
      formulas: [
        { name: "Grashof's Condition", eq: "s + l ≤ p + q (Grashof — at least one full rotation possible)", variables: { "s": "Shortest link length", "l": "Longest link length", "p, q": "Remaining two link lengths" } },
        { name: "Velocity of Coupler (graphical)", eq: "VB = VA + VBA (velocity polygon)", variables: { "VA": "Velocity of crank pin A (= ω₂ × r₂, perpendicular to crank)", "VBA": "Relative velocity of B w.r.t. A (perpendicular to coupler)" } },
        { name: "Mechanical Advantage", eq: "MA = sin(μ) / sin(α)", variables: { "μ": "Transmission angle at coupler-follower joint", "α": "Angle between input crank and coupler" } },
        { name: "Crank-Rocker Output Angle", eq: "cos(θ₄) = [k₁cos(θ₂) − k₂ + k₃cos(θ₂)] (Freudenstein's equation)", variables: { "k₁,k₂,k₃": "Link length ratios: d/a, d/c, (a²−b²+c²+d²)/(2ac)" } }
      ],
      explanation: "The four links are: (1) frame (fixed, length d), (2) input crank (length a), (3) coupler (length b), (4) output rocker or crank (length c). As the input crank rotates, the position of all other links is determined by the closure constraint — the loop must remain closed. Position analysis uses the vector loop equation: a·e^(iθ₂) + b·e^(iθ₃) = d + c·e^(iθ₄). Separating real and imaginary parts and solving gives θ₃ and θ₄ as functions of θ₂ (input angle). Velocity and acceleration analysis follow by differentiating with respect to time."
    },
    practicalRules: [
      "Design for transmission angle <strong>40° ≤ μ ≤ 140°</strong> throughout the working range of motion.",
      "For a crank-rocker: s + l ≤ p + q AND the shortest link (s) must be the crank or frame.",
      "For a double-crank (Grashof): fix the shortest link as the frame — both adjacent links rotate.",
      "Watt's linkage (approximate straight line motion from coupler): historically used in steam engines before precision machining.",
      "Quick-return ratio: time for forward stroke / return stroke. Depends on link ratios. Useful in machine tools (slow cutting, fast return).",
      "Check for <strong>toggle positions</strong> (μ = 0° or 180°) — mechanism locks (infinite mechanical advantage, zero velocity). Avoid in working range; exploit in locking mechanisms."
    ],
    workedExample: {
      problem: "A four-bar linkage has links: frame d = 150 mm, crank a = 50 mm, coupler b = 120 mm, rocker c = 100 mm. Check Grashof's condition and classify the mechanism. Find the transmission angle when the crank is at θ₂ = 90°.",
      given: ["a = 50 mm (crank)", "b = 120 mm (coupler)", "c = 100 mm (rocker)", "d = 150 mm (frame)"],
      steps: [
        { text: "Identify shortest (s) and longest (l) links:", calc: "s = 50 mm (crank, link a)\nl = 150 mm (frame, link d)\np = 120 mm, q = 100 mm" },
        { text: "Check Grashof's condition: s + l ≤ p + q?", calc: "s + l = 50 + 150 = 200 mm\np + q = 120 + 100 = 220 mm\n200 ≤ 220 ✓ → Grashof mechanism" },
        { text: "Identify inversion: which link is fixed?", calc: "Frame (d = 150 mm = longest) is fixed. Shortest link (a = 50 mm) is adjacent to fixed link.\n→ Grashof crank-rocker (crank makes full rotation, rocker oscillates)" },
        { text: "Transmission angle at θ₂ = 90° (crank vertical, crank pin B at top):", calc: "Position of A: (0, 0). Position of B: (a·cos90°, a·sin90°) = (0, 50 mm)\nD = (150, 0) mm (other frame pin).\nDB = √(150² + 50²) = √(22500+2500) = √25000 = 158.1 mm\nUsing cosine rule in triangle DBC:\ncos(μ) = (b² + c² − DB²)/(2bc) = (120² + 100² − 158.1²)/(2×120×100)\n= (14400 + 10000 − 24996)/(24000) = −596/24000 = −0.0248\nμ = arccos(−0.0248) = 91.4°" }
      ],
      answer: "Grashof mechanism (200 < 220). With frame fixed, shortest link (crank) makes full rotation → crank-rocker mechanism. Transmission angle at θ₂ = 90° is μ = 91.4° — excellent (close to 90°, maximum mechanical advantage)."
    },
    commonMistakes: [
      { title: "Applying Grashof's condition without identifying which link is fixed", desc: "Grashof's condition only tells you if full rotation is possible — not which link will rotate. The inversion (which link is fixed) determines the mechanism type. Students often say 'it's Grashof, so it's a crank-rocker' without checking which link is fixed." },
      { title: "Confusing the four link names", desc: "The four terms are frame (fixed), crank (input, makes full rotation), coupler (connects crank to follower), and rocker/follower (output). Students sometimes call the coupler the 'follower' — which leads to confusion with cam-follower terminology." },
      { title: "Ignoring transmission angle limits", desc: "A mathematically valid mechanism (Grashof, no toggle in working range) can still be a poor design if the transmission angle drops below 40°. Students check Grashof but skip the transmission angle — leading to mechanisms that bind or require excessive input torque." }
    ],
    simulation: "four-bar",
    realWorldUses: [
      { title: "Windscreen Wiper Mechanism", icon: "🚗", description: "Tandem wiper systems use a four-bar crank-rocker linkage to convert the motor's rotation into the wiper's oscillating sweep. The coupler curve is carefully designed so both wipers stay synchronised and clear the maximum area." },
      { title: "Front-End Loader Arm", icon: "🚜", description: "The bucket linkage on a front-end loader is a four-bar mechanism designed so the bucket remains approximately level throughout the lifting stroke — even though the main arm rotates. This 'self-levelling' behaviour is achieved by choosing link lengths so the bucket coupler undergoes nearly pure translation." },
      { title: "Folding Bicycle Mechanism", icon: "🚲", description: "Brompton and Dahon folding bikes use four-bar linkages to fold the frame — the geometry ensures the bike folds into a compact package with a single, smooth motion. The mechanism locks in both folded and open positions using toggle geometry." },
      { title: "Reciprocating Engine Valve Gear", icon: "🏭", description: "Stephenson's valve gear (19th century steam locomotives) used four-bar linkages to control valve timing, reversing direction, and cut-off from a single eccentric on the driving axle — one of the most ingenious mechanism designs in engineering history." }
    ],
    resources: [
      { label: "Four-Bar Linkage — NPTEL TOM", url: "https://nptel.ac.in/courses/112105127", type: "course" },
      { label: "Mechanisms & Machines (YouTube)", url: "https://www.youtube.com/watch?v=n0Gn0CaB4c8", type: "video" },
      { label: "MIT OCW — Machine Elements", url: "https://ocw.mit.edu/courses/2-72-elements-of-mechanical-design-spring-2009/", type: "course" }
    ]
  },

  {
    id: "flywheel", title: "Flywheel & Energy Fluctuation",
    category: "tom", icon: "⭕",
    tags: ["TOM", "flywheel", "energy fluctuation", "coefficient of fluctuation", "moment of inertia"],
    shortDesc: "Smoothing the jerky power delivery of engines and presses — the physics of rotational energy storage.",
    theory: {
      definition: "A flywheel is a heavy rotating disc or wheel that stores kinetic energy and releases it to smooth out fluctuations in angular velocity. In reciprocating engines, torque output varies cyclically — the flywheel absorbs energy during the power stroke and releases it during exhaust, intake, and compression strokes. In press machines and punch presses, the flywheel stores energy between punching operations and releases it instantly during the cutting stroke.",
      keyConcepts: [
        { term: "Coefficient of Fluctuation of Speed (Cs)", desc: "Cs = (ωmax − ωmin)/ωmean. Acceptable values: IC engines Cs = 1/100–1/200 (0.5–1%), pumps Cs = 1/30–1/50 (2–3%), punch presses Cs = 1/10–1/20 (5–10%). Lower Cs requires a larger, heavier flywheel. Cs is the primary design specification." },
        { term: "Maximum Fluctuation of Energy (ΔE)", desc: "The maximum change in kinetic energy during a cycle = area between the torque curve and mean torque line on a crank angle diagram. ΔE = Cs × I × ω²mean. This is the energy the flywheel must store and release per cycle." },
        { term: "Moment of Inertia (I)", desc: "I = ΔE/(Cs × ω²mean). The required moment of inertia. For a thin disc: I = ½mR². For a ring flywheel (mass concentrated at rim): I = mR² (more efficient). Real flywheels have a hub, arms, and rim — calculated as sum of parts." },
        { term: "Energy-Crank Angle Diagram", desc: "Plot of torque (or angular work done) vs crank angle for one complete cycle. Draw a mean torque line. Areas above = energy supplied to flywheel; areas below = energy taken from flywheel. The maximum fluctuation ΔE is the largest positive or negative swing on the cumulative energy curve." }
      ],
      formulas: [
        { name: "Coefficient of Fluctuation of Speed", eq: "Cs = (ωmax − ωmin) / ωmean", variables: { "ωmax, ωmin": "Maximum and minimum angular velocities in the cycle (rad/s)", "ωmean": "(ωmax + ωmin)/2 ≈ 2πN/60 for small fluctuations" } },
        { name: "Maximum Fluctuation of Energy", eq: "ΔE = Cs × I × ωmean²", variables: { "I": "Mass moment of inertia of flywheel (kg·m²)", "ΔE": "Energy to be stored/released (J)" } },
        { name: "Required Moment of Inertia", eq: "I = ΔE / (Cs × ωmean²)", variables: { "ΔE": "From energy-crank angle diagram (J)" } },
        { name: "Rim Flywheel Mass", eq: "ΔE = m × v²mean × Cs", variables: { "m": "Mass of flywheel rim (kg)", "vmean": "Mean rim velocity = ωmean × R (m/s)", "Typical vmean": "30–50 m/s for cast iron flywheels" } }
      ],
      explanation: "The energy-crank angle diagram is constructed by integrating the net torque (engine torque minus mean resistance torque) with respect to crank angle. Where net torque is positive, energy flows into the flywheel (ω increases). Where negative, energy flows out (ω decreases). The maximum total energy swing ΔE is the difference between the highest and lowest cumulative energy values. The flywheel must provide this ΔE while limiting the speed fluctuation to Cs. Since KE = ½Iω², and ΔKE = I×ωmean×Δω = I×ωmean²×Cs, we get I = ΔE/(Cs×ωmean²). A larger I (heavier flywheel) gives smaller Cs (smoother running) — but increases engine weight and cost."
    },
    practicalRules: [
      "Punch press flywheel: Cs = <strong>1/10 to 1/20</strong>. The flywheel stores energy between punches and releases it in the <strong>short punch stroke</strong> — typical punch time is <1% of cycle time.",
      "IC engine flywheel: Cs = <strong>1/100 to 1/200</strong> (very smooth) — large flywheel needed. Modern smooth-running multi-cylinder engines reduce ΔE, allowing smaller flywheels.",
      "Rim velocity limit: cast iron <strong>35–40 m/s</strong>, steel <strong>50–60 m/s</strong> — above this, centrifugal bursting becomes the failure mode.",
      "In automotive manual gearboxes, the flywheel also serves as the driven plate of the clutch — adding surface area constraint to the design.",
      "Dual-mass flywheels (DMF): primary and secondary flywheel connected by springs — filter torsional vibration before it reaches the gearbox. Used in all modern diesel passenger cars.",
      "Energy density of flywheel (J/kg) = ½(v_tip)² × σ_tensile/ρ at burst speed — carbon fibre flywheels store 200–400 Wh/kg (vs 30–80 Wh/kg for cast iron)."
    ],
    workedExample: {
      problem: "A single-cylinder IC engine runs at 600 RPM. The turning moment diagram gives a maximum fluctuation of energy ΔE = 1500 J per cycle. Design a cast iron flywheel with Cs = 1/150. The flywheel is a solid disc. Find: required moment of inertia I and flywheel diameter if the disc is 80 mm thick with ρ_CI = 7200 kg/m³.",
      given: ["N = 600 RPM → ω = 2π×600/60 = 62.83 rad/s", "ΔE = 1500 J", "Cs = 1/150", "Rim: solid disc, t = 80 mm, ρ = 7200 kg/m³"],
      steps: [
        { text: "Required moment of inertia:", calc: "I = ΔE/(Cs × ω²) = 1500 / ((1/150) × 62.83²)\n= 1500 / (0.00667 × 3947.6)\n= 1500 / 26.32 = 57.0 kg·m²" },
        { text: "For a solid disc: I = ½mR² = ½ρπR²tR² = ½ρπtR⁴. Solve for R:", calc: "R⁴ = 2I/(ρπt) = 2×57.0/(7200×π×0.08)\n= 114/(1809.6) = 0.06300 m⁴\nR = (0.0630)^0.25 = 0.501 m" },
        { text: "Diameter and mass:", calc: "D = 2R = 1.002 m ≈ 1.0 m\nm = ρ × π × R² × t = 7200 × π × 0.501² × 0.08 = 7200 × 0.0630 = 453 kg" },
        { text: "Verify I:", calc: "I = ½ × 453 × 0.501² = 0.5 × 453 × 0.251 = 56.9 kg·m² ≈ 57 kg·m² ✓" }
      ],
      answer: "Required I = 57.0 kg·m². Flywheel diameter = 1.0 m, mass = 453 kg (heavy — typical for a single-cylinder engine). The large mass is needed because single-cylinder engines have a very large ΔE relative to mean torque compared to multi-cylinder engines."
    },
    commonMistakes: [
      { title: "Confusing Cs (speed fluctuation) with Cf (energy fluctuation)", desc: "Cs = (ωmax−ωmin)/ωmean is coefficient of fluctuation of SPEED. Cf (or TCf) sometimes refers to the torque/energy fluctuation ratio = ΔE/(mean torque × cycle). These are different quantities with different values. Always specify which coefficient you are using." },
      { title: "Forgetting to use ω in rad/s (not RPM) in the formula", desc: "I = ΔE/(Cs × ω²) requires ω in rad/s. Using N in RPM gives I 3600 times too small. Always convert: ω = 2πN/60." },
      { title: "Reading ΔE incorrectly from the energy diagram", desc: "ΔE is the maximum swing in cumulative energy — NOT the area of the largest single loop. If the cumulative energy has a maximum at point A and minimum at point B, ΔE = E_A − E_B regardless of path between them. Students sometimes take the area of just one positive or negative zone." }
    ],
    simulation: "flywheel",
    realWorldUses: [
      { title: "Automobile Engine Flywheel", icon: "🚗", description: "A 1.4L 4-cylinder engine flywheel: ~6 kg, 300 mm diameter, Cs ≈ 1/200. Even with 4 power strokes per revolution (at 1500 RPM), some energy smoothing is needed. The flywheel also provides the inertia for engine startup via the starter motor ring gear." },
      { title: "Industrial Punch Press", icon: "🏭", description: "A 500-tonne punch press has a flywheel storing ~100 kJ. Punching stroke takes 0.05 s (50 ms) — flywheel releases 100 kJ at 600 RPM, giving average punch power of 2 MW from a 30 kW motor. The motor slowly recharges the flywheel over the remaining 1 s cycle." },
      { title: "Grid-Scale Energy Storage", icon: "⚡", description: "Carbon-fibre composite flywheels (Beacon Power) spin at 16,000 RPM in vacuum — storing 25 kWh per unit. Used for grid frequency regulation, absorbing and releasing energy in milliseconds. 200 units at 5 MW provide fast-response storage cheaper than batteries for this application." },
      { title: "Formula 1 KERS", icon: "🏎️", description: "Mechanical KERS (Kinetic Energy Recovery System) — used briefly in F1 2009 — used a steel flywheel spinning at 60,000 RPM in vacuum, storing 400 kJ and delivering 60 kW for 6 seconds per lap via a CVT. Replaced by the more powerful MGU-K electrical system in 2014 hybrid rules." }
    ],
    resources: [
      { label: "Flywheel Design — NPTEL TOM", url: "https://nptel.ac.in/courses/112105127", type: "course" },
      { label: "Turning Moment & Flywheel (YouTube)", url: "https://www.youtube.com/watch?v=McZq7aqPbX4", type: "video" },
      { label: "Engineering Toolbox — Flywheel Energy", url: "https://www.engineeringtoolbox.com/flywheel-d_1306.html", type: "article" }
    ]
  },

  {
    id: "rotor-balancing", title: "Balancing of Rotating Masses",
    category: "tom", icon: "⚖️",
    tags: ["dynamics", "vibration", "balancing", "rotor", "centrifugal", "mass"],
    shortDesc: "Eliminating destructive vibrations in high-speed machinery by counteracting unbalanced centrifugal forces.",
    theory: {
      definition: "When the center of mass of a rotating body does not align perfectly with its axis of rotation, an unbalanced centrifugal force is generated. This force rotates with the shaft, causing severe vibrations, bearing wear, and potential catastrophic failure at high speeds. Balancing is the process of adding or removing mass to ensure the principal axis of inertia aligns with the axis of rotation. There are two types: Static Balancing (balancing forces in a single plane) and Dynamic Balancing (balancing both forces and couples across multiple planes).",
      keyConcepts: [
        { term: "Static Unbalance", desc: "Occurs when the center of gravity is displaced radially from the axis of rotation, but the principal axis is parallel to it. This can be corrected by adding a single mass in the same plane to counteract the centrifugal force (ΣF = 0). The rotor would be out of balance even when stationary." },
        { term: "Dynamic Unbalance", desc: "Occurs when the principal axis of inertia intersects the axis of rotation at the center of gravity, but is tilted relative to it. Even if statically balanced (ΣF = 0), rotating the shaft creates a centrifugal couple (moment) that tries to twist the shaft. Dynamic balancing requires at least two correction planes (ΣF = 0 and ΣM = 0)." },
        { term: "Centrifugal Force", desc: "The unbalanced force is proportional to the unbalance mass (m), its radial distance (r), and the square of the angular velocity (ω²). Force = m·r·ω². Because it scales with ω², a small unbalance at 100 RPM becomes 100 times worse at 1000 RPM." },
        { term: "Vector Polygons", desc: "Graphical method for balancing. Unbalanced forces (m·r) are drawn as vectors tip-to-tail. To balance the system, the polygon must close. The closing vector represents the required balancing mass and its angular position." }
      ],
      formulas: [
        { name: "Centrifugal Force", eq: "F_c = m · r · ω²", variables: { "m": "Mass (kg)", "r": "Radius of center of mass (m)", "ω": "Angular velocity (rad/s)" } },
        { name: "Force Balance (Static)", eq: "Σ (m_i · r_i · cos θ_i) = 0\nΣ (m_i · r_i · sin θ_i) = 0", variables: {} },
        { name: "Couple Balance (Dynamic)", eq: "Σ (m_i · r_i · l_i · cos θ_i) = 0\nΣ (m_i · r_i · l_i · sin θ_i) = 0", variables: { "l_i": "Axial distance from reference plane" } }
      ],
      explanation: "Imagine a washing machine with wet clothes clumped on one side. As it spins, the unbalanced mass creates a rotating centrifugal force. At low speeds, you feel a wobble. At high spin speeds, the machine shakes violently. To balance it, we could add a counterweight exactly opposite the clothes (static balance). However, in a long cylinder like a car's driveshaft or a jet engine turbine, the unbalances might be at different ends. Even if their forces cancel out, they create a twisting moment (couple). We must add counterweights at two distinct planes (e.g., front and rear of the rotor) to achieve true dynamic balance."
    },
    practicalRules: [
      "Any rigid rotor, no matter how complex the unbalance distribution, can be completely dynamically balanced by adding or removing mass in exactly <strong>two arbitrary correction planes</strong>.",
      "Unbalance is typically measured in <strong>gram-millimeters (g·mm)</strong>. ISO 1940 standard dictates acceptable unbalance grades (e.g., G6.3 for pump impellers, G2.5 for gas turbines, G0.4 for gyroscopes).",
      "Because centrifugal force increases with the square of speed, high-speed rotors (turbines, turbochargers spinning at 100,000+ RPM) require extreme precision balancing.",
      "Balancing is usually achieved by drilling shallow holes (removing mass) or attaching small clips/weights (adding mass) at the calculated angle."
    ],
    workedExample: {
      problem: "A shaft carries three masses in the same plane: m₁ = 4 kg at r₁ = 75 mm, θ₁ = 0°; m₂ = 3 kg at r₂ = 85 mm, θ₂ = 60°; m₃ = 2.5 kg at r₃ = 50 mm, θ₃ = 135°. Find the balancing mass m_b required at a radius r_b = 100 mm to achieve static balance.",
      given: ["m₁r₁ = 4 × 75 = 300 kg·mm at 0°", "m₂r₂ = 3 × 85 = 255 kg·mm at 60°", "m₃r₃ = 2.5 × 50 = 125 kg·mm at 135°", "r_b = 100 mm"],
      steps: [
        { text: "Calculate horizontal (X) components of m·r vectors:", calc: "ΣH = m₁r₁cos(0°) + m₂r₂cos(60°) + m₃r₃cos(135°)\n= 300(1) + 255(0.5) + 125(-0.707)\n= 300 + 127.5 - 88.38 = 339.12 kg·mm" },
        { text: "Calculate vertical (Y) components of m·r vectors:", calc: "ΣV = m₁r₁sin(0°) + m₂r₂sin(60°) + m₃r₃sin(135°)\n= 300(0) + 255(0.866) + 125(0.707)\n= 0 + 220.83 + 88.38 = 309.21 kg·mm" },
        { text: "Calculate resultant unbalance vector (R):", calc: "R = √(ΣH² + ΣV²)\n= √(339.12² + 309.21²)\n= √(115002 + 95611) = √210613 = 458.9 kg·mm\nAngle θ_R = atan2(309.21, 339.12) = 42.36°" },
        { text: "Determine balancing mass:", calc: "The balancing vector must be equal and opposite to R.\nm_b · r_b = R\nm_b × 100 = 458.9\nm_b = 4.589 kg\nAngle θ_b = θ_R + 180° = 42.36° + 180° = 222.36°" }
      ],
      answer: "A mass of 4.59 kg must be placed at a radius of 100 mm, at an angle of 222.4° to achieve static balance."
    },
    commonMistakes: [
      { title: "Assuming static balance is enough for long rotors", desc: "A car wheel or a thin disc can often just be statically balanced. But a long cylinder (like an electric motor armature) must be dynamically balanced. If you only statically balance it, you might introduce a massive unbalance couple that will destroy the bearings." },
      { title: "Ignoring the effect of operating speed", desc: "A rotor might run smoothly at 1000 RPM, but pass through a critical speed (resonance) at 1500 RPM, where even tiny unbalances cause huge deflections. Rotors operating above critical speeds (flexible rotors) require complex multi-plane balancing." }
    ],
    simulation: "rotor-balancing",
    realWorldUses: [
      { title: "Automotive Wheel Balancing", icon: "🚗", description: "When you get new tires, the wheel is spun on a dynamic balancing machine. The machine detects unbalance and tells the mechanic to hammer small lead/zinc weights (e.g., 15 grams) onto the inner and outer rim (two-plane dynamic balancing) to prevent steering wheel shimmy at highway speeds." },
      { title: "Jet Engine Turbines", icon: "✈️", description: "Turbine blades and compressor spools must be perfectly balanced. Unbalance causes vibration that can shatter the ceramic blade coatings, rub against the casing, or fatigue the main shaft bearings." },
      { title: "Hard Disk Drives", icon: "💾", description: "The platters in high-performance hard drives spin at 10,000 to 15,000 RPM. They are dynamically balanced during manufacturing using lasers to ablate tiny amounts of material from the spindle hub." }
    ],
    resources: [
      { label: "Static vs Dynamic Balancing", url: "https://www.youtube.com/watch?v=1xNMcYQ4R1k", type: "video" },
      { label: "NPTEL — Dynamics of Machines (Balancing)", url: "https://nptel.ac.in/courses/112104114", type: "course" }
    ]
  }

);
